USE gavin;
CREATE TABLE IF NOT EXISTS orders (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NULL,customer_name VARCHAR(120) NOT NULL,customer_email VARCHAR(190) NOT NULL,customer_phone VARCHAR(40) NOT NULL,address TEXT NOT NULL,postal_code VARCHAR(30) NOT NULL,notes TEXT NULL,subtotal DECIMAL(14,2) NOT NULL DEFAULT 0,shipping DECIMAL(14,2) NOT NULL DEFAULT 0,total DECIMAL(14,2) NOT NULL DEFAULT 0,status ENUM('pending','paid','processing','shipped','delivered','cancelled') NOT NULL DEFAULT 'pending',payment_status ENUM('unpaid','paid','failed','refunded') NOT NULL DEFAULT 'unpaid',payment_reference VARCHAR(190) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,INDEX(status,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS order_items (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id INT UNSIGNED NOT NULL,product_id INT UNSIGNED NULL,seller_id INT UNSIGNED NULL,product_title VARCHAR(180) NOT NULL,unit_price DECIMAL(14,2) NOT NULL,quantity INT NOT NULL,line_total DECIMAL(14,2) NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE SET NULL,FOREIGN KEY(seller_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS payments (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id INT UNSIGNED NOT NULL,gateway VARCHAR(50) NOT NULL,authority VARCHAR(190) NULL,ref_id VARCHAR(190) NULL,amount DECIMAL(14,2) NOT NULL,status ENUM('initiated','success','failed','cancelled') NOT NULL DEFAULT 'initiated',raw_response TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB;
