USE gavin;
ALTER TABLE users ADD COLUMN phone VARCHAR(40) NULL;
ALTER TABLE users ADD COLUMN address TEXT NULL;
ALTER TABLE users ADD COLUMN postal_code VARCHAR(30) NULL;
ALTER TABLE users ADD COLUMN payout_account VARCHAR(190) NULL;
ALTER TABLE users ADD COLUMN payout_gateway VARCHAR(80) NULL;
ALTER TABLE users ADD COLUMN payout_status ENUM('not_configured','pending','verified') DEFAULT 'not_configured';
ALTER TABLE users ADD COLUMN platform_fee_percent DECIMAL(5,2) DEFAULT 10.00;

CREATE TABLE IF NOT EXISTS categories (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,user_id INT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
